### ISSUE TITLE
Use SQL standard OFFSET .. FETCH instead of ROW_NUMBER() pagination for Derby

### ISSUE THREAD

**Issue by lukaseder** [nurkiewicz/spring-data-jdbc-repository#19]
I've had a brief review of your solution and found that you're using `ROW_NUMBER() OVER()` window functions for pagination in Derby:
https://github.com/nurkiewicz/spring-data-jdbc-repository/blob/master/src/main/java/com/nurkiewicz/jdbcrepository/sql/DerbySqlGenerator.java#L13

But Derby supports the SQL standard `OFFSET .. FETCH` clause:
http://db.apache.org/derby/docs/10.6/ref/rrefsqljoffsetfetch.html

Why aren't you using that instead?

**Comment by nurkiewicz** [comment]
Thank you very much, indeed you are right. I guess I was misguided by [official FAQ (point 5.2)](http://db.apache.org/derby/faq.html) suggesting `OFFSET ... FETCH` was introduced in 10.7 - but apprently it's already available in [10.5](http://db.apache.org/derby/docs/10.5/ref/rrefsqljoffsetfetch.html). Once again thanks for reporting this.

**Comment by lukaseder** [comment]
Sure, no worries. I just learned that Derby has partial support for window functions :)
